"""init

Revision ID: 392e971f7759
Revises: 
Create Date: 2026-06-02 15:18:31.073663
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Identifiants de révision utilisés par Alembic
revision: str = '392e971f7759'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('oracle_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('mana_cost', sa.String(length=100), nullable=True),
    sa.Column('mana_value', sa.Float(), nullable=True),
    sa.Column('type_line', sa.String(length=255), nullable=True),
    sa.Column('oracle_text', sa.Text(), nullable=True),
    sa.Column('power', sa.String(length=10), nullable=True),
    sa.Column('toughness', sa.String(length=10), nullable=True),
    sa.Column('loyalty', sa.String(length=10), nullable=True),
    sa.Column('defense', sa.String(length=10), nullable=True),
    sa.Column('colors', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('color_identity', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('legal_commander', sa.Boolean(), nullable=False),
    sa.Column('edhrec_rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_name'), 'cards', ['name'], unique=False)
    op.create_index(op.f('ix_cards_normalized_name'), 'cards', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_cards_oracle_id'), 'cards', ['oracle_id'], unique=True)
    op.create_table('import_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cards_imported', sa.Integer(), nullable=False),
    sa.Column('printings_imported', sa.Integer(), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mtg_sets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('set_type', sa.String(length=50), nullable=True),
    sa.Column('released_at', sa.Date(), nullable=True),
    sa.Column('block', sa.String(length=100), nullable=True),
    sa.Column('parent_set_code', sa.String(length=16), nullable=True),
    sa.Column('card_count', sa.Integer(), nullable=True),
    sa.Column('icon_svg_uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mtg_sets_code'), 'mtg_sets', ['code'], unique=True)
    op.create_table('card_faces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('face_name', sa.String(length=255), nullable=False),
    sa.Column('mana_cost', sa.String(length=100), nullable=True),
    sa.Column('type_line', sa.String(length=255), nullable=True),
    sa.Column('oracle_text', sa.Text(), nullable=True),
    sa.Column('power', sa.String(length=10), nullable=True),
    sa.Column('toughness', sa.String(length=10), nullable=True),
    sa.Column('loyalty', sa.String(length=10), nullable=True),
    sa.Column('defense', sa.String(length=10), nullable=True),
    sa.Column('colors', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('image_small', sa.Text(), nullable=True),
    sa.Column('image_normal', sa.Text(), nullable=True),
    sa.Column('image_large', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_faces_card_id'), 'card_faces', ['card_id'], unique=False)
    op.create_table('card_printings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scryfall_id', sa.String(length=36), nullable=False),
    sa.Column('oracle_id', sa.String(length=36), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('set_code', sa.String(length=16), nullable=True),
    sa.Column('collector_number', sa.String(length=20), nullable=True),
    sa.Column('lang', sa.String(length=10), nullable=True),
    sa.Column('rarity', sa.String(length=20), nullable=True),
    sa.Column('released_at', sa.Date(), nullable=True),
    sa.Column('artist', sa.String(length=255), nullable=True),
    sa.Column('border_color', sa.String(length=20), nullable=True),
    sa.Column('frame', sa.String(length=20), nullable=True),
    sa.Column('full_art', sa.Boolean(), nullable=False),
    sa.Column('promo', sa.Boolean(), nullable=False),
    sa.Column('reprint', sa.Boolean(), nullable=False),
    sa.Column('digital', sa.Boolean(), nullable=False),
    sa.Column('image_small', sa.Text(), nullable=True),
    sa.Column('image_normal', sa.Text(), nullable=True),
    sa.Column('image_large', sa.Text(), nullable=True),
    sa.Column('scryfall_uri', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_code'], ['mtg_sets.code'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_printings_card_id'), 'card_printings', ['card_id'], unique=False)
    op.create_index(op.f('ix_card_printings_oracle_id'), 'card_printings', ['oracle_id'], unique=False)
    op.create_index(op.f('ix_card_printings_scryfall_id'), 'card_printings', ['scryfall_id'], unique=True)
    op.create_index(op.f('ix_card_printings_set_code'), 'card_printings', ['set_code'], unique=False)
    op.create_table('card_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('printing_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('price_type', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['printing_id'], ['card_printings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('printing_id', 'date', 'source', 'currency', 'price_type', name='uq_card_prices_printing_date_type')
    )
    op.create_index(op.f('ix_card_prices_date'), 'card_prices', ['date'], unique=False)
    op.create_index(op.f('ix_card_prices_printing_id'), 'card_prices', ['printing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ATTENTION : ne jamais lancer downgrade en production
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_prices_printing_id'), table_name='card_prices')
    op.drop_index(op.f('ix_card_prices_date'), table_name='card_prices')
    op.drop_table('card_prices')
    op.drop_index(op.f('ix_card_printings_set_code'), table_name='card_printings')
    op.drop_index(op.f('ix_card_printings_scryfall_id'), table_name='card_printings')
    op.drop_index(op.f('ix_card_printings_oracle_id'), table_name='card_printings')
    op.drop_index(op.f('ix_card_printings_card_id'), table_name='card_printings')
    op.drop_table('card_printings')
    op.drop_index(op.f('ix_card_faces_card_id'), table_name='card_faces')
    op.drop_table('card_faces')
    op.drop_index(op.f('ix_mtg_sets_code'), table_name='mtg_sets')
    op.drop_table('mtg_sets')
    op.drop_table('import_runs')
    op.drop_index(op.f('ix_cards_oracle_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_normalized_name'), table_name='cards')
    op.drop_index(op.f('ix_cards_name'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
