#!/usr/bin/env python3
"""
generate_annotations.py

Génère cluster_annotations.json et cluster_taxonomy.json
à partir des annotations expertes codées directement dans ce fichier.
"""
from __future__ import annotations

import json
import logging
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

LOG_DIR = ROOT / "logs"
LOG_DIR.mkdir(exist_ok=True)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%H:%M:%S",
    handlers=[logging.StreamHandler(sys.stdout)],
)
log = logging.getLogger(__name__)

OUT_ANNOT = ROOT / "data" / "clustering" / "cluster_annotations.json"
OUT_TAXO  = ROOT / "data" / "clustering" / "cluster_taxonomy.json"
SUMMARY   = ROOT / "data" / "clustering" / "cluster_summary.csv"

TAXONOMY_FAMILIES = [
    "Tribal", "Graveyard", "Blink", "Aristocrats", "Tokens",
    "Lands", "Artifacts", "Enchantments", "Spellslinger", "Combo",
    "Ramp", "Control", "Aggro", "Autres",
]

# ── Annotations expertes ─────────────────────────────────────────────────────
# Chaque entrée : cluster_id, name, confidence, primary_strategy,
#                 mechanics, dominant_colors, dominant_types,
#                 tribe, description, representative_cards

RAW_ANNOTATIONS = [
    # ── Grands clusters (> 100 cartes) ───────────────────────────────────────
    {
        "cluster_id": 61,
        "name": "Aristocrats",
        "confidence": 0.92,
        "primary_strategy": "Aristocrats",
        "mechanics": ["Sacrifice", "Drain", "ETB", "Reanimation"],
        "dominant_colors": ["B", "W", "R"],
        "dominant_types": ["Creature", "Enchantment"],
        "tribe": None,
        "description": "Archétype basé sur le sacrifice de créatures pour drainer la vie des adversaires. Vampiric Tutor, Blood Artist, Zulaport Cutthroat et Viscera Seer sont les piliers du moteur sacrifice/drain.",
        "representative_cards": ["Zulaport Cutthroat", "Blood Artist", "Viscera Seer", "Vampiric Tutor", "Yawgmoth, Thran Physician"],
    },
    {
        "cluster_id": 53,
        "name": "Mardu Goodstuff",
        "confidence": 0.78,
        "primary_strategy": "Aggro",
        "mechanics": ["Combat", "Removal", "Recursion"],
        "dominant_colors": ["W", "B", "R"],
        "dominant_types": ["Creature", "Instant", "Sorcery"],
        "tribe": None,
        "description": "Package de lands et de sorts efficaces en couleurs Mardu (blanc/noir/rouge). Mana fixing et cartes polyvalentes pour decks agressifs ou de contrôle en trois couleurs.",
        "representative_cards": ["Path to Exile", "Sacred Foundry", "Ruinous Ultimatum", "Reconnaissance", "Selfless Spirit"],
    },
    {
        "cluster_id": 37,
        "name": "Simic Ramp",
        "confidence": 0.88,
        "primary_strategy": "Ramp",
        "mechanics": ["Ramp", "Land Fetch", "Token", "Landfall"],
        "dominant_colors": ["G", "U"],
        "dominant_types": ["Sorcery", "Creature", "Land"],
        "tribe": None,
        "description": "Moteur de rampe vert-bleu centré sur la recherche de terrains, les tokens landfall et les créatures vertes efficaces. Nature's Lore, Rampant Growth et Scute Swarm définissent le plan.",
        "representative_cards": ["Nature's Lore", "Rampant Growth", "Scute Swarm", "Seedborn Muse", "Natural Order"],
    },
    {
        "cluster_id": 95,
        "name": "Boros Angels",
        "confidence": 0.82,
        "primary_strategy": "Aggro",
        "mechanics": ["Combat", "Vigilance", "Lifegain", "Tokens"],
        "dominant_colors": ["W", "R"],
        "dominant_types": ["Creature", "Enchantment"],
        "tribe": "Angel",
        "description": "Cluster agressif blanc-rouge mêlant anges, combat répété (Aggravated Assault) et créatures de valeur. Aurelia, the Warleader et Avacyn, Angel of Hope sont les pièces maîtresses.",
        "representative_cards": ["Aurelia, the Warleader", "Avacyn, Angel of Hope", "Aggravated Assault", "Arid Mesa", "Blade Historian"],
    },
    {
        "cluster_id": 85,
        "name": "Sultai Goodstuff",
        "confidence": 0.75,
        "primary_strategy": "Control",
        "mechanics": ["Ramp", "Removal", "Card Draw", "Counters"],
        "dominant_colors": ["G", "U", "B"],
        "dominant_types": ["Land", "Creature", "Instant"],
        "tribe": None,
        "description": "Mana fixing et cartes efficaces en couleurs Sultai (vert/bleu/noir). Package de fetchlands et de cartes de valeur pour decks midrange ou contrôle en trois couleurs.",
        "representative_cards": ["Windswept Heath", "Three Visits", "Worldly Tutor", "Veil of Summer", "Yavimaya Elder"],
    },
    {
        "cluster_id": 58,
        "name": "Boros Equipment",
        "confidence": 0.87,
        "primary_strategy": "Aggro",
        "mechanics": ["Equipment", "Voltron", "Attach", "Double Strike"],
        "dominant_colors": ["W", "R"],
        "dominant_types": ["Artifact", "Creature", "Enchantment"],
        "tribe": None,
        "description": "Archétype équipement blanc-rouge. Smothering Tithe finance les équipements, Stoneforge Mystic les cherche, et Sunforger fournit de la réactivité. Package Voltron/combat.",
        "representative_cards": ["Smothering Tithe", "Stoneforge Mystic", "Sunforger", "Sword of Feast and Famine", "Sigarda's Aid"],
    },
    {
        "cluster_id": 36,
        "name": "Mono Blue Control",
        "confidence": 0.90,
        "primary_strategy": "Control",
        "mechanics": ["Counterspell", "Card Draw", "Bounce", "Clone"],
        "dominant_colors": ["U"],
        "dominant_types": ["Instant", "Sorcery", "Creature"],
        "tribe": None,
        "description": "Contrôle bleu pur : counters, pioche, défausse permanents et clones. Pull from Tomorrow, Ponder, Pongify et Rite of Replication définissent un plan de domination de la pile.",
        "representative_cards": ["Pull from Tomorrow", "Ponder", "Rite of Replication", "Rapid Hybridization", "Peregrine Drake"],
    },
    {
        "cluster_id": 25,
        "name": "Mill Dimir",
        "confidence": 0.82,
        "primary_strategy": "Combo",
        "mechanics": ["Mill", "Graveyard", "Proliferate", "Zombie"],
        "dominant_colors": ["U", "B"],
        "dominant_types": ["Creature", "Enchantment", "Sorcery"],
        "tribe": None,
        "description": "Archétype mill bleu-noir. Mindcrank, Mind Grind et Mesmeric Orb vident les bibliothèques. Muldrotha et Living Death exploitent ensuite le cimetière rempli.",
        "representative_cards": ["Mindcrank", "Mesmeric Orb", "Mind Grind", "Muldrotha, the Gravetide", "Living Death"],
    },
    {
        "cluster_id": 87,
        "name": "Spellslinger Blue",
        "confidence": 0.88,
        "primary_strategy": "Spellslinger",
        "mechanics": ["Instants", "Sorceries", "Tokens", "Card Draw"],
        "dominant_colors": ["U"],
        "dominant_types": ["Instant", "Sorcery", "Creature"],
        "tribe": None,
        "description": "Spellslinger bleu : lancement de nombreux sorts pour générer des tokens d'île, des poulpes ou déclencher des capacités. Leyline of Anticipation donne du flash, Murmuring Mystic et Metallurgic Summonings créent les tokens.",
        "representative_cards": ["Leyline of Anticipation", "Murmuring Mystic", "Metallurgic Summonings", "Jin-Gitaxias, Progress Tyrant", "Laboratory Maniac"],
    },
    {
        "cluster_id": 80,
        "name": "Golgari Midrange",
        "confidence": 0.78,
        "primary_strategy": "Ramp",
        "mechanics": ["Ramp", "Card Draw", "Graveyard", "Tokens"],
        "dominant_colors": ["G", "B"],
        "dominant_types": ["Creature", "Land", "Enchantment"],
        "tribe": None,
        "description": "Midrange vert-noir combinant rampe, pioche et moteur graveyard. Growth Spiral, Greater Good et Glen Elendra Archmage forment un moteur de valeur durable.",
        "representative_cards": ["Growth Spiral", "Greater Good", "Glen Elendra Archmage", "Growing Rites of Itlimoc", "Freed from the Real"],
    },
    # ── Clusters moyens (50-100 cartes) ──────────────────────────────────────
    {
        "cluster_id": 40,
        "name": "Boros Aggro Tokens",
        "confidence": 0.83,
        "primary_strategy": "Tokens",
        "mechanics": ["Tokens", "Combat", "Attack Triggers", "Double Strike"],
        "dominant_colors": ["W", "R"],
        "dominant_types": ["Creature", "Artifact"],
        "tribe": None,
        "description": "Aggro blanc-rouge basé sur les attaques répétées et les tokens. Isshin, Two Heavens as One double les triggers d'attaque, Helm of the Host et Hanweir Garrison génèrent des tokens.",
        "representative_cards": ["Isshin, Two Heavens as One", "Helm of the Host", "Hanweir Garrison", "Hero of Bladehold", "Hellrider"],
    },
    {
        "cluster_id": 31,
        "name": "Mono Blue Spellslinger",
        "confidence": 0.89,
        "primary_strategy": "Spellslinger",
        "mechanics": ["Instants", "Sorceries", "Flash", "Counterspell"],
        "dominant_colors": ["U"],
        "dominant_types": ["Instant", "Sorcery", "Creature"],
        "tribe": None,
        "description": "Spellslinger pur bleu : Talrand crée des drakes à chaque sort lancé, Snapcaster Mage recycle, et Spell Pierce / Stubborn Denial protègent. Plan contrôle-combo.",
        "representative_cards": ["Talrand, Sky Summoner", "Snapcaster Mage", "Spell Pierce", "Sublime Epiphany", "Stormtide Leviathan"],
    },
    {
        "cluster_id": 92,
        "name": "Boros Goblin Aggro",
        "confidence": 0.80,
        "primary_strategy": "Aggro",
        "mechanics": ["Combat", "Equipment", "Goblin Synergy", "Haste"],
        "dominant_colors": ["W", "R"],
        "dominant_types": ["Creature", "Artifact"],
        "tribe": None,
        "description": "Aggro blanc-rouge mélangeant goblins, équipements lourds (Colossus Hammer) et combat. Bruenor Battlehammer réduit le coût d'équipement.",
        "representative_cards": ["Conspicuous Snoop", "Bruenor Battlehammer", "Colossus Hammer", "Blood Moon", "Battle Cry Goblin"],
    },
    {
        "cluster_id": 67,
        "name": "Wizard Tribal",
        "confidence": 0.84,
        "primary_strategy": "Tribal",
        "mechanics": ["Wizard Synergy", "Card Draw", "Bounce", "Flash"],
        "dominant_colors": ["U"],
        "dominant_types": ["Creature", "Instant"],
        "tribe": "Wizard",
        "description": "Tribal sorcier bleu. Wavebreak Hippocamp donne de la pioche à chaque sort lancé au tour adverse, Wizard Class booste la tribu, et Vedalken Shackles contrôle le board.",
        "representative_cards": ["Wavebreak Hippocamp", "Wizard Class", "Vedalken Shackles", "Tishana's Tidebinder", "Triskaidekaphile"],
    },
    {
        "cluster_id": 72,
        "name": "Simic Lands Ramp",
        "confidence": 0.90,
        "primary_strategy": "Ramp",
        "mechanics": ["Ramp", "Land Untap", "Token", "Landfall"],
        "dominant_colors": ["G", "U"],
        "dominant_types": ["Creature", "Land", "Sorcery"],
        "tribe": None,
        "description": "Rampe verte-bleue maximale : Azusa joue 3 terrains par tour, Aesi pioche à chaque terrain posé, Ancient Greenwarden double les triggers landfall. Avenger of Zendikar conclut.",
        "representative_cards": ["Azusa, Lost but Seeking", "Aesi, Tyrant of Gyre Strait", "Avenger of Zendikar", "Allosaurus Shepherd", "Ancient Greenwarden"],
    },
    {
        "cluster_id": 98,
        "name": "Aristocrats Black",
        "confidence": 0.93,
        "primary_strategy": "Aristocrats",
        "mechanics": ["Sacrifice", "Drain", "Reanimation", "Token"],
        "dominant_colors": ["B"],
        "dominant_types": ["Creature", "Enchantment", "Artifact"],
        "tribe": None,
        "description": "Aristocrats mono-noir concentré. Blood Artist et Bastion of Remembrance drainent, Ashnod's Altar et Altar of Dementia sont les sacrificiers, Bitterblossom génère les tokens.",
        "representative_cards": ["Blood Artist", "Ashnod's Altar", "Bitterblossom", "Bolas's Citadel", "Bastion of Remembrance"],
    },
    {
        "cluster_id": 69,
        "name": "Mono Red Aggro",
        "confidence": 0.85,
        "primary_strategy": "Aggro",
        "mechanics": ["Haste", "Combat", "Double Strike", "Burn"],
        "dominant_colors": ["R"],
        "dominant_types": ["Creature", "Enchantment", "Instant"],
        "tribe": None,
        "description": "Aggro rouge pur : Fervor et Haste Magic donnent la vitesse, Fiery Emancipation triple les dégâts, Gisela, Blade of Goldnight double les dégâts infligés.",
        "representative_cards": ["Gisela, Blade of Goldnight", "Fervor", "Fiery Emancipation", "Faithless Looting", "Final Fortune"],
    },
    {
        "cluster_id": 74,
        "name": "Boros Midrange",
        "confidence": 0.74,
        "primary_strategy": "Control",
        "mechanics": ["Removal", "Combat", "Clone", "Recursion"],
        "dominant_colors": ["W", "R"],
        "dominant_types": ["Creature", "Instant", "Sorcery"],
        "tribe": None,
        "description": "Midrange blanc-rouge polyvalent. Dualcaster Mage et Delina copient les sorts, Day of Judgment et Drana and Linvala contrôlent le board.",
        "representative_cards": ["Drana and Linvala", "Day of Judgment", "Dualcaster Mage", "Delina, Wild Mage", "Darksteel Plate"],
    },
    {
        "cluster_id": 78,
        "name": "Elf Tribal Hydra",
        "confidence": 0.83,
        "primary_strategy": "Tribal",
        "mechanics": ["Elf Synergy", "+1/+1 Counters", "Ramp", "Landfall"],
        "dominant_colors": ["G"],
        "dominant_types": ["Creature"],
        "tribe": "Elf",
        "description": "Elfes et hydras en vert. Legolas, Master Biomancer et Managorger Hydra accumulent les marqueurs +1/+1. Décor Tolkien (Mirkwood, Lórien) marque l'inspiration thématique.",
        "representative_cards": ["Managorger Hydra", "Master Biomancer", "Legolas Greenleaf", "Llanowar Elves", "Llanowar Visionary"],
    },
    {
        "cluster_id": 100,
        "name": "Blue Cantrip Control",
        "confidence": 0.86,
        "primary_strategy": "Control",
        "mechanics": ["Card Draw", "Counterspell", "Bounce", "Theft"],
        "dominant_colors": ["U"],
        "dominant_types": ["Instant", "Sorcery"],
        "tribe": None,
        "description": "Contrôle bleu par cantrips et pioche massive. Brainstorm, Arcane Denial, Blue Sun's Zenith et Bribery forment un arsenal de valeur et de contrôle de ressources.",
        "representative_cards": ["Brainstorm", "Arcane Denial", "Archmage Emeritus", "Bribery", "Blue Sun's Zenith"],
    },
    {
        "cluster_id": 4,
        "name": "5-Color Dragons",
        "confidence": 0.91,
        "primary_strategy": "Tribal",
        "mechanics": ["Dragon Synergy", "Haste", "Ramp", "ETB"],
        "dominant_colors": ["R", "G", "U", "W", "B"],
        "dominant_types": ["Creature"],
        "tribe": "Dragon",
        "description": "Dragons 5 couleurs. Old Gnawbone génère des Trésors, Scourge of Valkas brûle à l'arrivée, Sarkhan amplifie la tribu. Savage Ventmaw et Ramos alimentent en mana.",
        "representative_cards": ["Old Gnawbone", "Scourge of Valkas", "Sarkhan Unbroken", "Savage Ventmaw", "Ramos, Dragon Engine"],
    },
    {
        "cluster_id": 90,
        "name": "Simic Evolve",
        "confidence": 0.80,
        "primary_strategy": "Combo",
        "mechanics": ["+1/+1 Counters", "Evolve", "ETB", "Token"],
        "dominant_colors": ["G", "U"],
        "dominant_types": ["Creature", "Enchantment"],
        "tribe": None,
        "description": "Moteur de compteurs et d'évolution vert-bleu. Fathom Mage pioche à chaque compteur placé, Ezuri's Predation nettoie le board, Faerie Artisans copie les créatures adverses.",
        "representative_cards": ["Fathom Mage", "Ezuri's Predation", "Felidar Retreat", "Eldritch Evolution", "Double Major"],
    },
    {
        "cluster_id": 81,
        "name": "Blue Tempo",
        "confidence": 0.80,
        "primary_strategy": "Control",
        "mechanics": ["Bounce", "Counterspell", "Flash", "Card Draw"],
        "dominant_colors": ["U"],
        "dominant_types": ["Instant", "Creature", "Sorcery"],
        "tribe": None,
        "description": "Tempo bleu : Hullbreaker Horror rebondit les permanents à l'arrivée de sorts, Illusionist's Stratagem recycle les créatures, Into the Roil et Imprisoned in the Moon contrôlent.",
        "representative_cards": ["Hullbreaker Horror", "Illusionist's Stratagem", "Into the Roil", "Isochron Scepter", "Imprisoned in the Moon"],
    },
    {
        "cluster_id": 43,
        "name": "Simic Counters",
        "confidence": 0.83,
        "primary_strategy": "Combo",
        "mechanics": ["+1/+1 Counters", "Proliferate", "Token", "Card Draw"],
        "dominant_colors": ["G", "U"],
        "dominant_types": ["Creature", "Enchantment"],
        "tribe": None,
        "description": "Accumulation de marqueurs +1/+1 en vert-bleu. Simic Ascendancy gagne la partie à 20 marqueurs, Rishkar untape les créatures avec compteurs pour du mana, Roalesk prolifère.",
        "representative_cards": ["Simic Ascendancy", "Rishkar, Peema Renegade", "Roalesk, Apex Hybrid", "Song of Freyalise", "Selvala, Explorer Returned"],
    },
    {
        "cluster_id": 75,
        "name": "Mono White Control",
        "confidence": 0.86,
        "primary_strategy": "Control",
        "mechanics": ["Board Wipe", "Removal", "Tax", "Prison"],
        "dominant_colors": ["W"],
        "dominant_types": ["Creature", "Instant", "Sorcery"],
        "tribe": None,
        "description": "Contrôle blanc : Drannith Magistrate empêche de jouer depuis d'autres zones, Elesh Norn écrase le board, Farewell et Final Showdown balaient massivement. Esper Sentinel taxe les sorts.",
        "representative_cards": ["Elesh Norn, Grand Cenobite", "Drannith Magistrate", "Farewell", "Enlightened Tutor", "Esper Sentinel"],
    },
    {
        "cluster_id": 33,
        "name": "Dimir Pain Draw",
        "confidence": 0.81,
        "primary_strategy": "Control",
        "mechanics": ["Card Draw", "Damage", "Discard", "Tutor"],
        "dominant_colors": ["U", "B"],
        "dominant_types": ["Enchantment", "Creature", "Sorcery"],
        "tribe": None,
        "description": "Archétype punitif bleu-noir : Phyrexian Arena et Peer into the Abyss piocher massivement mais douleur, Phyrexian Tyranny inflige des dégâts pour chaque carte piochée par les adversaires.",
        "representative_cards": ["Phyrexian Arena", "Phyrexian Tyranny", "Peer into the Abyss", "Nin, the Pain Artist", "Ob Nixilis, the Hate-Twisted"],
    },
    {
        "cluster_id": 56,
        "name": "Mono Black Tutor",
        "confidence": 0.88,
        "primary_strategy": "Control",
        "mechanics": ["Tutor", "Removal", "Board Wipe", "Ramp"],
        "dominant_colors": ["B"],
        "dominant_types": ["Instant", "Sorcery"],
        "tribe": None,
        "description": "Package de tuteurs et de suppression noirs. Demonic Tutor, Dark Ritual, Damnation et Decree of Pain forment le cœur d'un contrôle noir redoutable.",
        "representative_cards": ["Demonic Tutor", "Dark Ritual", "Damnation", "Diabolic Intent", "Decree of Pain"],
    },
    {
        "cluster_id": 52,
        "name": "Vampire Lifegain",
        "confidence": 0.87,
        "primary_strategy": "Tribal",
        "mechanics": ["Lifegain", "Vampire Synergy", "Drain", "Token"],
        "dominant_colors": ["W", "B"],
        "dominant_types": ["Creature", "Enchantment"],
        "tribe": "Vampire",
        "description": "Tribal vampire blanc-noir centré sur le gain de vie et le drain. Soul Warden et Soul's Attendant incrémentent la vie, Sorin Imperious Bloodlord accélère les vampires, Skullclamp pioche.",
        "representative_cards": ["Sorin, Imperious Bloodlord", "Soul Warden", "Skullclamp", "Speaker of the Heavens", "Taborax, Hope's Demise"],
    },
    {
        "cluster_id": 44,
        "name": "Green Stompy",
        "confidence": 0.78,
        "primary_strategy": "Aggro",
        "mechanics": ["Counters", "Ramp", "Big Creatures", "Token"],
        "dominant_colors": ["G"],
        "dominant_types": ["Creature", "Enchantment"],
        "tribe": None,
        "description": "Créatures vertes massives avec compteurs. Steel Leaf Champion, Stonehoof Chieftain et Stumpsquall Hydra sont des menaces imposantes. Squirrel Nest et Second Harvest génèrent des tokens.",
        "representative_cards": ["Steel Leaf Champion", "Stonehoof Chieftain", "Slimefoot, the Stowaway", "Song of Freyalise", "Squirrel Nest"],
    },
    {
        "cluster_id": 102,
        "name": "Blue Counterspell",
        "confidence": 0.90,
        "primary_strategy": "Control",
        "mechanics": ["Counterspell", "Card Draw", "Clone", "Bounce"],
        "dominant_colors": ["U"],
        "dominant_types": ["Instant", "Sorcery", "Creature"],
        "tribe": None,
        "description": "Pile de contresorts bleus. Cryptic Command, Disallow, Disdainful Stroke et Dramatic Reversal forment une muraille de contresorts. Drown in Dreams pioche et remplit la bibliothèque.",
        "representative_cards": ["Cryptic Command", "Disallow", "Disdainful Stroke", "Drown in Dreams", "Clone Legion"],
    },
    # ── Dragon clusters ───────────────────────────────────────────────────────
    {
        "cluster_id": 0,
        "name": "Dragon Tribal UG",
        "confidence": 0.93,
        "primary_strategy": "Tribal",
        "mechanics": ["Dragon Synergy", "Card Draw", "Haste", "ETB"],
        "dominant_colors": ["U", "G"],
        "dominant_types": ["Creature"],
        "tribe": "Dragon",
        "description": "Tribal dragon vert-bleu. Kindred Discovery pioche un dragon à chaque attaque, Lathliss crée des jetons dragón, Miirym duplique chaque dragon qui arrive.",
        "representative_cards": ["Kindred Discovery", "Lathliss, Dragon Queen", "Miirym, Sentinel Wyrm", "Korlessa, Scale Singer", "Haven of the Spirit Dragon"],
    },
    {
        "cluster_id": 3,
        "name": "Dragon Ramp RG",
        "confidence": 0.94,
        "primary_strategy": "Tribal",
        "mechanics": ["Dragon Synergy", "Haste", "Ramp", "Burn"],
        "dominant_colors": ["R", "G"],
        "dominant_types": ["Creature", "Enchantment"],
        "tribe": "Dragon",
        "description": "Package rouge-vert de support dragon. Dragon Tempest haste + brûle, Dragonspeaker Shaman et Dragonlord's Servant réduisent les coûts, Dragon's Hoard génère du mana.",
        "representative_cards": ["Dragon Tempest", "Dragonspeaker Shaman", "Dragon's Hoard", "Crux of Fate", "Drakuseth, Maw of Flames"],
    },
    {
        "cluster_id": 7,
        "name": "Dragon Tribal Multicolor",
        "confidence": 0.91,
        "primary_strategy": "Tribal",
        "mechanics": ["Dragon Synergy", "ETB", "Haste", "Treasure"],
        "dominant_colors": ["R", "G", "U", "W", "B"],
        "dominant_types": ["Creature"],
        "tribe": "Dragon",
        "description": "Dragons multicolores aux effets dévastateurs : Atarka, World Render double-strike, Ancient Copper Dragon crée des Trésors, Balefire Dragon brûle toutes les créatures adverses.",
        "representative_cards": ["Balefire Dragon", "Atarka, World Render", "Ancient Copper Dragon", "Ancient Silver Dragon", "Ancient Gold Dragon"],
    },
    {
        "cluster_id": 27,
        "name": "Dragon Bomb RG",
        "confidence": 0.92,
        "primary_strategy": "Tribal",
        "mechanics": ["Dragon Synergy", "ETB Trigger", "Haste", "Flying"],
        "dominant_colors": ["R", "G"],
        "dominant_types": ["Creature", "Enchantment"],
        "tribe": "Dragon",
        "description": "Dragons rouges-verts explosifs. Terror of the Peaks brûle à chaque créature qui arrive, Utvara Hellkite crée des 6/6 à chaque attaque de dragon, Temur Ascendancy donne le haste.",
        "representative_cards": ["Terror of the Peaks", "Utvara Hellkite", "Temur Ascendancy", "Tiamat", "Thundermaw Hellkite"],
    },
    {
        "cluster_id": 26,
        "name": "Dragon Grixis",
        "confidence": 0.85,
        "primary_strategy": "Tribal",
        "mechanics": ["Dragon Synergy", "Sneak Attack", "Haste", "Counter"],
        "dominant_colors": ["U", "B", "R"],
        "dominant_types": ["Creature"],
        "tribe": "Dragon",
        "description": "Dragons en couleurs Grixis (bleu/noir/rouge). Sneak Attack déploie les gros dragons sans payer leur coût, Silumgar's Scorn protège, Stormbreath Dragon est immunisé au blanc.",
        "representative_cards": ["Sneak Attack", "Stormbreath Dragon", "Steel Hellkite", "Silumgar's Scorn", "Shivan Devastator"],
    },
    # ── Goblin clusters ───────────────────────────────────────────────────────
    {
        "cluster_id": 10,
        "name": "Goblin Tribal Core",
        "confidence": 0.96,
        "primary_strategy": "Tribal",
        "mechanics": ["Goblin Synergy", "Haste", "Aggro", "Tutor"],
        "dominant_colors": ["R"],
        "dominant_types": ["Creature"],
        "tribe": "Goblin",
        "description": "Noyau tribal goblin rouge. Goblin Matron et Goblin Recruiter tuteurisent les pièces, Goblin Chieftain et Goblin King boostent la tribu, Goblin Bombardment sacrifie pour des dégâts.",
        "representative_cards": ["Goblin Bombardment", "Goblin Matron", "Goblin Chieftain", "Goblin Lackey", "Goblin Recruiter"],
    },
    {
        "cluster_id": 11,
        "name": "Goblin Aggro Tokens",
        "confidence": 0.94,
        "primary_strategy": "Tribal",
        "mechanics": ["Goblin Synergy", "Token", "Haste", "Warchief"],
        "dominant_colors": ["R"],
        "dominant_types": ["Creature"],
        "tribe": "Goblin",
        "description": "Essaim de goblins agressifs. Goblin Warchief donne haste et réduction de coût, Hobgoblin Bandit Lord booste, Muxus déploie des goblins depuis le dessus de la bibliothèque.",
        "representative_cards": ["Goblin Warchief", "Goblin Recruiter", "Muxus, Goblin Grandee", "Goblin Piledriver", "Hobgoblin Bandit Lord"],
    },
    {
        "cluster_id": 34,
        "name": "Goblin Token Swarm",
        "confidence": 0.93,
        "primary_strategy": "Tribal",
        "mechanics": ["Goblin Synergy", "Token", "Haste", "Tap Ability"],
        "dominant_colors": ["R"],
        "dominant_types": ["Creature", "Sorcery"],
        "tribe": "Goblin",
        "description": "Essaim de jetons goblins. Krenko génère exponentiellement des goblins, Pashalik Mons sacrifie pour des dégâts, Mana Echoes accumule du mana avec la tribu.",
        "representative_cards": ["Krenko, Tin Street Kingpin", "Pashalik Mons", "Muxus, Goblin Grandee", "Mana Echoes", "Legion Warboss"],
    },
    # ── Autres clusters ───────────────────────────────────────────────────────
    {
        "cluster_id": 30,
        "name": "Orzhov Lifegain",
        "confidence": 0.83,
        "primary_strategy": "Aristocrats",
        "mechanics": ["Lifegain", "Drain", "Token", "Recursion"],
        "dominant_colors": ["W", "B"],
        "dominant_types": ["Creature", "Enchantment"],
        "tribe": None,
        "description": "Gain de vie et drain blanc-noir. Kambal, Impassioned Orator et Lunarch Veteran incrémentent la vie, Luminous Broodmoth revient des morts, Kaya's Wrath nettoie.",
        "representative_cards": ["Kambal, Profiteering Mayor", "Luminous Broodmoth", "Kaya's Wrath", "Legion's Landing", "Markov Purifier"],
    },
    {
        "cluster_id": 39,
        "name": "Boros Voltron",
        "confidence": 0.78,
        "primary_strategy": "Aggro",
        "mechanics": ["Equipment", "Aura", "Voltron", "Double Strike"],
        "dominant_colors": ["W", "R"],
        "dominant_types": ["Artifact", "Creature"],
        "tribe": None,
        "description": "Voltron blanc-rouge : empiler équipements et auras sur un commandant pour tuer en combat. Kaldra Compleat, Jeska et Magnetic Theft forment le package.",
        "representative_cards": ["Kaldra Compleat", "Jeska, Thrice Reborn", "Guttersnipe", "Lion Sash", "Inspiring Vantage"],
    },
    {
        "cluster_id": 91,
        "name": "Vampire Tribal Black",
        "confidence": 0.90,
        "primary_strategy": "Tribal",
        "mechanics": ["Vampire Synergy", "Token", "Drain", "Flying"],
        "dominant_colors": ["B"],
        "dominant_types": ["Creature"],
        "tribe": "Vampire",
        "description": "Tribal vampire mono-noir. Bloodline Keeper génère des jetons vampire, Bloodlord of Vaasgoth booste à chaque tour, Anowon sacrifie les créatures adverses.",
        "representative_cards": ["Bloodline Keeper", "Bloodlord of Vaasgoth", "Anowon, the Ruin Sage", "Blade of the Bloodchief", "Astarion, the Decadent"],
    },
    {
        "cluster_id": 64,
        "name": "Counter Doubling",
        "confidence": 0.82,
        "primary_strategy": "Combo",
        "mechanics": ["+1/+1 Counters", "Doubling", "ETB", "Token"],
        "dominant_colors": ["W", "G"],
        "dominant_types": ["Creature", "Enchantment"],
        "tribe": None,
        "description": "Doublement de marqueurs +1/+1. Corpsejack Menace et Citadel Siege accumulent les compteurs, Conclave Mentor double les marqueurs Vert, Elite Scaleguard et Dawnhart Wardens exploitent la masse.",
        "representative_cards": ["Corpsejack Menace", "Citadel Siege", "Conclave Mentor", "Crystalline Crawler", "Death's Presence"],
    },
    {
        "cluster_id": 42,
        "name": "White Weenie Tokens",
        "confidence": 0.79,
        "primary_strategy": "Tokens",
        "mechanics": ["Token", "Weenie", "+1/+1 Counters", "Card Draw"],
        "dominant_colors": ["W"],
        "dominant_types": ["Creature"],
        "tribe": None,
        "description": "Weenie blanc créant des tokens et accumulant des compteurs. Mikaeus, the Lunarch distribue des +1/+1, Luminarch Aspirant en place un par tour, Mentor of the Meek pioche.",
        "representative_cards": ["Mikaeus, the Lunarch", "Luminarch Aspirant", "Mentor of the Meek", "Loyal Retainers", "Mirran Crusader"],
    },
    {
        "cluster_id": 32,
        "name": "Esper Artifacts",
        "confidence": 0.87,
        "primary_strategy": "Artifacts",
        "mechanics": ["Artifact Synergy", "Affinity", "Thopter", "Control"],
        "dominant_colors": ["W", "U", "B"],
        "dominant_types": ["Artifact", "Creature"],
        "tribe": None,
        "description": "Artifacts en Esper (blanc/bleu/noir). Tezzeret maîtrise les artefacts et se défend, Thought Monitor piocher avec l'affinité, The Reality Chip fournit un oracle permanent.",
        "representative_cards": ["Tezzeret the Seeker", "Thought Monitor", "The Reality Chip", "Supreme Verdict", "Teferi, Time Raveler"],
    },
    {
        "cluster_id": 73,
        "name": "Dinosaur Tribal",
        "confidence": 0.91,
        "primary_strategy": "Tribal",
        "mechanics": ["Dinosaur Synergy", "Enrage", "Ramp", "Big Creatures"],
        "dominant_colors": ["G", "W"],
        "dominant_types": ["Creature"],
        "tribe": "Dinosaur",
        "description": "Tribal dinosaure vert-blanc. Tolsimir ami des loups partage l'espace avec les dinosaures via Zacama, Gishath et Wrathful Raptors. Gros corps enrage et accélération.",
        "representative_cards": ["Zacama, Primal Calamity", "Wayward Swordtooth", "Wrathful Raptors", "Tolsimir Wolfblood", "Xenagos, God of Revels"],
    },
    {
        "cluster_id": 101,
        "name": "Blue Draw Control",
        "confidence": 0.84,
        "primary_strategy": "Control",
        "mechanics": ["Card Draw", "Counterspell", "Bounce", "Token"],
        "dominant_colors": ["U"],
        "dominant_types": ["Instant", "Sorcery", "Creature"],
        "tribe": None,
        "description": "Contrôle bleu par pioche. Chrome Host Seedshark crée des Incubateurs à chaque sort non-créature, Coastal Piracy pioche en combat, Cancel et Condescend contrent.",
        "representative_cards": ["Chrome Host Seedshark", "Coastal Piracy", "Castle Vantress", "Consuming Tide", "Commander's Insight"],
    },
    {
        "cluster_id": 99,
        "name": "Blue Bounce Control",
        "confidence": 0.82,
        "primary_strategy": "Control",
        "mechanics": ["Bounce", "Counterspell", "Card Draw", "Stax"],
        "dominant_colors": ["U"],
        "dominant_types": ["Instant", "Sorcery"],
        "tribe": None,
        "description": "Contrôle bleu par retour en main. Frantic Search, Flood of Tears, Filter Out et Forbid retournent tous les permanents adverses. Guile contre et garde les sorts.",
        "representative_cards": ["Frantic Search", "Flood of Tears", "Filter Out", "Foil", "Guile"],
    },
    {
        "cluster_id": 19,
        "name": "Elf Tribal Core",
        "confidence": 0.97,
        "primary_strategy": "Tribal",
        "mechanics": ["Elf Synergy", "Ramp", "Swarm", "Anthem"],
        "dominant_colors": ["G"],
        "dominant_types": ["Creature"],
        "tribe": "Elf",
        "description": "Tribal elfe mono-vert concentré. Elvish Archdruid génère du mana massif, Elvish Warmaster crée des jetons, Ezuri, Renegade Leader et Elvish Champion donnent de la force et de la forestwalk.",
        "representative_cards": ["Elvish Archdruid", "Elvish Warmaster", "Ezuri, Renegade Leader", "Elvish Mystic", "Dwynen's Elite"],
    },
    {
        "cluster_id": 65,
        "name": "White Tribal Support",
        "confidence": 0.79,
        "primary_strategy": "Tribal",
        "mechanics": ["Anthem", "Token", "Board Wipe", "Tutor"],
        "dominant_colors": ["W"],
        "dominant_types": ["Creature", "Enchantment", "Sorcery"],
        "tribe": None,
        "description": "Support tribal blanc généraliste. Unclaimed Territory fixe le mana tribal, Vanquisher's Banner pioche et booste, Wrath of God et Vanquish the Horde gèrent le board.",
        "representative_cards": ["Unclaimed Territory", "Vanquisher's Banner", "Wrath of God", "Unbreakable Formation", "White Plume Adventurer"],
    },
    {
        "cluster_id": 77,
        "name": "Zombie Tribal",
        "confidence": 0.87,
        "primary_strategy": "Tribal",
        "mechanics": ["Zombie Synergy", "Graveyard", "Token", "Sacrifice"],
        "dominant_colors": ["B", "U"],
        "dominant_types": ["Creature"],
        "tribe": "Zombie",
        "description": "Tribal zombie bleu-noir. Grimgrin, Gisa et Geralf et Gravespawn Sovereign sont les piliers. Ghoulish Procession génère des tokens, Go for the Throat supprime.",
        "representative_cards": ["Grimgrin, Corpse-Born", "Gisa, the Hellraiser", "Geralf, the Fleshwright", "God-Eternal Bontu", "Ghoulcaller Gisa"],
    },
    {
        "cluster_id": 49,
        "name": "Mardu Warriors",
        "confidence": 0.74,
        "primary_strategy": "Aggro",
        "mechanics": ["Combat", "Warriors", "Haste", "Double Strike"],
        "dominant_colors": ["W", "B", "R"],
        "dominant_types": ["Creature", "Enchantment"],
        "tribe": "Warrior",
        "description": "Aggro Mardu guerrier. Nobilis of War booste les attaquants, Otharri Suns'Glory crée des tokens rebelles à chaque attaque, Open the Armory cherche les équipements.",
        "representative_cards": ["Nobilis of War", "Otharri, Suns'Glory", "Open the Armory", "Nomad Outpost", "Pact Weapon"],
    },
    {
        "cluster_id": 46,
        "name": "Dimir Reanimator",
        "confidence": 0.81,
        "primary_strategy": "Graveyard",
        "mechanics": ["Reanimation", "Graveyard", "Self-Mill", "Control"],
        "dominant_colors": ["U", "B"],
        "dominant_types": ["Creature", "Sorcery"],
        "tribe": None,
        "description": "Réanimation bleu-noir. Sepulchral Primordial ramène les créatures des cimetières adverses, Sheoldred redevient du cimetière, Startled Awake mille puis revient.",
        "representative_cards": ["Sheoldred, Whispering One", "Sepulchral Primordial", "Startled Awake", "Sire of Stagnation", "Sewer Nemesis"],
    },
    {
        "cluster_id": 51,
        "name": "Azorius Blink",
        "confidence": 0.84,
        "primary_strategy": "Blink",
        "mechanics": ["Blink", "ETB", "Flash", "Card Draw"],
        "dominant_colors": ["W", "U"],
        "dominant_types": ["Creature", "Instant"],
        "tribe": None,
        "description": "Blink blanc-bleu. Archaeomancer revient du cimetière avec un sort, Agent of Treachery vole les permanents à chaque blink, Abuelo exile et revient. Plan ETB répétés.",
        "representative_cards": ["Archaeomancer", "Agent of Treachery", "Abuelo, Ancestral Echo", "Approach of the Second Sun", "Azorius Signet"],
    },
    {
        "cluster_id": 93,
        "name": "Mono Red Value",
        "confidence": 0.76,
        "primary_strategy": "Aggro",
        "mechanics": ["Impulse Draw", "Treasure", "Haste", "ETB"],
        "dominant_colors": ["R"],
        "dominant_types": ["Creature", "Artifact", "Sorcery"],
        "tribe": None,
        "description": "Rouge valeur : Decadent Dragon crée des Trésors et impulse-pioche, Chimil the Inner Sun cascade chaque tour, Crime Novelist accumule des Trésors depuis les sorts rouges.",
        "representative_cards": ["Decadent Dragon", "Chimil, the Inner Sun", "Crime Novelist", "Chandra, Torch of Defiance", "Crackle with Power"],
    },
    {
        "cluster_id": 86,
        "name": "Human Tribal Tokens",
        "confidence": 0.86,
        "primary_strategy": "Tribal",
        "mechanics": ["Human Synergy", "Token", "+1/+1 Counters", "Anthem"],
        "dominant_colors": ["W", "G"],
        "dominant_types": ["Creature", "Enchantment"],
        "tribe": "Human",
        "description": "Tribal humain blanc-vert. Heronblade Elite et Katilda génèrent du mana des humains, Gavony Township place des +1/+1, Increasing Devotion déploie cinq humains.",
        "representative_cards": ["Heronblade Elite", "Katilda, Dawnhart Prime", "Gavony Township", "Increasing Devotion", "Hamlet Vanguard"],
    },
    {
        "cluster_id": 55,
        "name": "Mill Dimir Alt",
        "confidence": 0.89,
        "primary_strategy": "Combo",
        "mechanics": ["Mill", "Self-Mill", "Graveyard", "Horror"],
        "dominant_colors": ["U", "B"],
        "dominant_types": ["Creature", "Sorcery", "Enchantment"],
        "tribe": None,
        "description": "Mill alternatif bleu-noir centré sur le remplissage du cimetière adverse. Grazilaxx pioche à chaque fois qu'une créature n'est pas bloquée, Fraying Sanity double le mill, Hedron Crab mille à chaque terrain.",
        "representative_cards": ["Grazilaxx, Illithid Scholar", "Hedron Crab", "Glimpse the Unthinkable", "Fraying Sanity", "Fleet Swallower"],
    },
    {
        "cluster_id": 45,
        "name": "Golgari Reanimate",
        "confidence": 0.85,
        "primary_strategy": "Graveyard",
        "mechanics": ["Reanimation", "Sacrifice", "Graveyard", "Self-Mill"],
        "dominant_colors": ["B", "G"],
        "dominant_types": ["Creature", "Sorcery"],
        "tribe": None,
        "description": "Réanimation vert-noir. Reanimate ramène les gros corps, Prossh sacrifie les tokens pour du mana, Savra sacrifie les créatures pour des effets, Ruthless Technomancer ramène des artefacts.",
        "representative_cards": ["Reanimate", "Prossh, Skyraider of Kher", "Savra, Queen of the Golgari", "Ruthless Technomancer", "Rise from the Grave"],
    },
    {
        "cluster_id": 88,
        "name": "Simic Lands Counters",
        "confidence": 0.80,
        "primary_strategy": "Lands",
        "mechanics": ["+1/+1 Counters", "Land Synergy", "Proliferate", "Bounce"],
        "dominant_colors": ["G", "U"],
        "dominant_types": ["Creature", "Land"],
        "tribe": None,
        "description": "Synergies terrains et marqueurs vert-bleu. Karn's Bastion prolifère, Kodama of the West Tree joue des terrains depuis le dessus, Khalni Heart Expedition cherche des terrains.",
        "representative_cards": ["Karn's Bastion", "Kodama of the West Tree", "Khalni Heart Expedition", "Karametra, God of Harvests", "Kalonian Hydra"],
    },
    {
        "cluster_id": 48,
        "name": "Rakdos Vampire",
        "confidence": 0.83,
        "primary_strategy": "Tribal",
        "mechanics": ["Vampire Synergy", "Flying", "Drain", "Control"],
        "dominant_colors": ["B", "R"],
        "dominant_types": ["Creature", "Sorcery"],
        "tribe": "Vampire",
        "description": "Vampires Rakdos (noir/rouge). Olivia Voldaren vole les créatures adverses, Olivia, Crimson Bride réanime les vampires, Neheb génère du mana rouge post-combat.",
        "representative_cards": ["Olivia Voldaren", "Olivia, Crimson Bride", "Necropolis Regent", "Neheb, the Eternal", "Mortify"],
    },
    {
        "cluster_id": 15,
        "name": "Phyrexian Infect",
        "confidence": 0.95,
        "primary_strategy": "Combo",
        "mechanics": ["Infect", "Proliferate", "Poison Counters", "Flying"],
        "dominant_colors": ["W", "U", "B", "G"],
        "dominant_types": ["Creature", "Enchantment"],
        "tribe": None,
        "description": "Archétype Phyrexian infecte : Phyresis Outbreak et Prolifogue à Phyresis donnent rapidement des compteurs de poison. Norn's Choirmaster prolifère, Phyrexian Swarmlord crée des insectes infectés.",
        "representative_cards": ["Prologue to Phyresis", "Phyresis Outbreak", "Phyrexian Swarmlord", "Norn's Choirmaster", "Plague Stinger"],
    },
    {
        "cluster_id": 16,
        "name": "Proliferate Counters",
        "confidence": 0.93,
        "primary_strategy": "Combo",
        "mechanics": ["Proliferate", "+1/+1 Counters", "Infect", "Oil Counters"],
        "dominant_colors": ["W", "U", "B", "G"],
        "dominant_types": ["Creature", "Enchantment"],
        "tribe": None,
        "description": "Prolifération massive de marqueurs. Evolution Sage prolifère à chaque terrain posé, Inexorable Tide à chaque sort, Flux Channeler à chaque sort non-créature. Ixhel et Ezuri finissent le travail.",
        "representative_cards": ["Evolution Sage", "Inexorable Tide", "Flux Channeler", "Ixhel, Scion of Atraxa", "Glistening Sphere"],
    },
    {
        "cluster_id": 76,
        "name": "Dinosaur Ramp Naya",
        "confidence": 0.88,
        "primary_strategy": "Tribal",
        "mechanics": ["Dinosaur Synergy", "Ramp", "Big Creatures", "Trample"],
        "dominant_colors": ["R", "G", "W"],
        "dominant_types": ["Creature", "Land"],
        "tribe": "Dinosaur",
        "description": "Dinosaures Naya avec rampe aggressive. Gishath, Sun's Avatar déploie des dinosaures en attaquant, Marauding Raptor réduit les coûts, Kinjalli's Caller accélère la courbe.",
        "representative_cards": ["Gishath, Sun's Avatar", "Marauding Raptor", "Kinjalli's Caller", "Gyre Sage", "Kessig Wolf Run"],
    },
    {
        "cluster_id": 2,
        "name": "Changeling Tribal",
        "confidence": 0.85,
        "primary_strategy": "Tribal",
        "mechanics": ["Changeling", "Tribal Synergy", "All Creature Types"],
        "dominant_colors": ["W", "U", "B", "R", "G"],
        "dominant_types": ["Creature"],
        "tribe": "Changeling",
        "description": "Changelings qui activent toutes les synergies tribales simultanément. Irregular Cohort, Graveshifter et Guardian Gladewalker bénéficient de tous les lords et synergies.",
        "representative_cards": ["Irregular Cohort", "Graveshifter", "Guardian Gladewalker", "Gangly Stompling", "Knight Exemplar"],
    },
    {
        "cluster_id": 5,
        "name": "Shapeshifter Tribal",
        "confidence": 0.88,
        "primary_strategy": "Tribal",
        "mechanics": ["Changeling", "Clone", "Tribal Synergy", "All Types"],
        "dominant_colors": ["G", "U"],
        "dominant_types": ["Creature"],
        "tribe": "Shapeshifter",
        "description": "Shapeshifters et changelings avec Maskwood Nexus qui rend tout le monde de toutes les tribus. Mirror Entity booste massivement, Reaper King détruit les permanents.",
        "representative_cards": ["Maskwood Nexus", "Mirror Entity", "Reaper King", "Mutavault", "Moritte of the Frost"],
    },
    {
        "cluster_id": 68,
        "name": "Selesnya Counters",
        "confidence": 0.80,
        "primary_strategy": "Aggro",
        "mechanics": ["+1/+1 Counters", "Anthem", "Token", "Landfall"],
        "dominant_colors": ["W", "G"],
        "dominant_types": ["Creature"],
        "tribe": None,
        "description": "Compteurs et anthems blanc-vert. Adeline crée des soldats en attaquant, Abzan Falconer donne le vol aux créatures avec compteurs, Augur of Autumn joue des créatures depuis le dessus.",
        "representative_cards": ["Adeline, Resplendent Cathar", "Abzan Falconer", "Augur of Autumn", "Avacyn's Pilgrim", "Angel of Glory's Rise"],
    },
    {
        "cluster_id": 62,
        "name": "Edgar Vampire Token",
        "confidence": 0.91,
        "primary_strategy": "Tribal",
        "mechanics": ["Vampire Synergy", "Token", "Lifegain", "Drain"],
        "dominant_colors": ["W", "B"],
        "dominant_types": ["Creature"],
        "tribe": "Vampire",
        "description": "Tribal vampire Edgar-style avec production de jetons. Elenda crée des jetons en mourant, Drana libère les vampires, Edgar, Charmed Groom génère des jetons vampire.",
        "representative_cards": ["Elenda, the Dusk Rose", "Drana, Liberator of Malakir", "Edgar, Charmed Groom", "Exquisite Blood", "Forerunner of the Legion"],
    },
    {
        "cluster_id": 23,
        "name": "Dimir Artifacts",
        "confidence": 0.86,
        "primary_strategy": "Artifacts",
        "mechanics": ["Artifact Synergy", "Affinity", "Flying", "Control"],
        "dominant_colors": ["U", "B"],
        "dominant_types": ["Artifact", "Creature"],
        "tribe": None,
        "description": "Artefacts bleu-noir. Cranial Plating booste massivement, Darksteel Forge rend les artefacts indestructibles, Academy Ruins recycle depuis le cimetière, Baleful Strix pioche et vole.",
        "representative_cards": ["Baleful Strix", "Cranial Plating", "Darksteel Forge", "Academy Ruins", "Bronze Guardian"],
    },
    {
        "cluster_id": 21,
        "name": "Naya Dinosaurs Stompy",
        "confidence": 0.82,
        "primary_strategy": "Tribal",
        "mechanics": ["Dinosaur Synergy", "Enrage", "Trample", "Big Creatures"],
        "dominant_colors": ["R", "G", "W"],
        "dominant_types": ["Creature"],
        "tribe": "Dinosaur",
        "description": "Gros dinosaures Naya. Temple Altisaur réduit les dégâts sur les dinos avec compteurs, Shalai and Hallar prolifèrent, Scytheclaw Raptor et Silverclad Ferocidons dominent le combat.",
        "representative_cards": ["Temple Altisaur", "Shalai and Hallar", "Runic Armasaur", "Savage Stomp", "Shifting Ceratops"],
    },
    {
        "cluster_id": 54,
        "name": "Dimir Mill",
        "confidence": 0.87,
        "primary_strategy": "Combo",
        "mechanics": ["Mill", "Graveyard", "Bounce", "Self-Mill"],
        "dominant_colors": ["U", "B"],
        "dominant_types": ["Creature", "Enchantment", "Sorcery"],
        "tribe": None,
        "description": "Mill Dimir concentré. Duskmantle Guildmage combiné à Mindcrank crée une boucle infinie de mill/drain. Drown in the Loch contrecarre et exile selon la taille du cimetière.",
        "representative_cards": ["Duskmantle Guildmage", "Drowned Secrets", "Drown in the Loch", "Elder Brain", "Endless Evil"],
    },
    {
        "cluster_id": 6,
        "name": "Dinosaur Gruul",
        "confidence": 0.89,
        "primary_strategy": "Tribal",
        "mechanics": ["Dinosaur Synergy", "Ramp", "Big Creatures", "Enrage"],
        "dominant_colors": ["R", "G"],
        "dominant_types": ["Creature", "Land"],
        "tribe": "Dinosaur",
        "description": "Dinosaures rouge-vert. Etali plonge dans les bibliothèques adverses en attaquant, Apex Altisaur cascade à travers les autres dinosaures, Earthshaker Dreadmaw piétine.",
        "representative_cards": ["Etali, Primal Conqueror", "Apex Altisaur", "Earthshaker Dreadmaw", "Gishath, Sun's Avatar", "Carnage Tyrant"],
    },
    {
        "cluster_id": 59,
        "name": "Orzhov Cleric",
        "confidence": 0.81,
        "primary_strategy": "Tribal",
        "mechanics": ["Cleric Synergy", "Lifegain", "Token", "Sacrifice"],
        "dominant_colors": ["W", "B"],
        "dominant_types": ["Creature"],
        "tribe": "Cleric",
        "description": "Tribal clerc blanc-noir. Edgewalker réduit le coût des clercs, Elas il-Kor drains à la mort/arrivée des créatures, Drana the Last Bloodchief réanime. Doubtless One grossit avec les clercs.",
        "representative_cards": ["Elas il-Kor, Sadistic Pilgrim", "Edgewalker", "Drana, the Last Bloodchief", "Doubtless One", "Dark Supplicant"],
    },
    {
        "cluster_id": 24,
        "name": "Phyrexian Poison",
        "confidence": 0.94,
        "primary_strategy": "Combo",
        "mechanics": ["Infect", "Proliferate", "Poison Counters", "Trample"],
        "dominant_colors": ["G", "U", "B"],
        "dominant_types": ["Creature", "Sorcery"],
        "tribe": None,
        "description": "Archétype poison Phyrexian concentré. Blighted Agent est indétectable avec l'infect, Bloated Contaminator prolifère en attaquant avec trample, Contagion Engine prolifère deux fois.",
        "representative_cards": ["Blighted Agent", "Bloated Contaminator", "Contagion Engine", "Drown in Ichor", "Core Prowler"],
    },
    {
        "cluster_id": 38,
        "name": "Boros Aggro Small",
        "confidence": 0.73,
        "primary_strategy": "Aggro",
        "mechanics": ["Combat", "Haste", "Double Strike", "Exalted"],
        "dominant_colors": ["W", "R"],
        "dominant_types": ["Creature", "Enchantment"],
        "tribe": None,
        "description": "Petit aggro blanc-rouge. Lightning Runner gagne des tours supplémentaires avec énergie, Leonin Warleader crée des jetons en attaquant, Lovisa Coldeyes booste les barbares et guerriers.",
        "representative_cards": ["Leonin Warleader", "Lightning Runner", "Lovisa Coldeyes", "Lunar Frenzy", "Lightning Mauler"],
    },
    {
        "cluster_id": 9,
        "name": "Changeling Support",
        "confidence": 0.82,
        "primary_strategy": "Tribal",
        "mechanics": ["Changeling", "Tribal Synergy", "Token", "All Types"],
        "dominant_colors": ["W", "U", "B", "R", "G"],
        "dominant_types": ["Creature"],
        "tribe": "Changeling",
        "description": "Support aux changelings et synergies tribales génériques. Banner of Kinship, Cloudshredder Sliver et Chameleon Colossus s'adaptent à n'importe quelle tribu.",
        "representative_cards": ["Banner of Kinship", "Chameleon Colossus", "Cloudshredder Sliver", "Bloodline Pretender", "Changeling Wayfinder"],
    },
    {
        "cluster_id": 17,
        "name": "Azorius Blink Alt",
        "confidence": 0.85,
        "primary_strategy": "Blink",
        "mechanics": ["Blink", "ETB", "Exile", "Flicker"],
        "dominant_colors": ["W", "U"],
        "dominant_types": ["Creature", "Instant"],
        "tribe": None,
        "description": "Blink blanc-bleu alternatif. Restoration Angel exile et revient instantanément, Preston, the Vanisher crée des tokens illusionnistes à chaque exile, Roon of the Hidden Realm est le commandant prototypique.",
        "representative_cards": ["Restoration Angel", "Preston, the Vanisher", "Roon of the Hidden Realm", "Reflector Mage", "Shrieking Drake"],
    },
    {
        "cluster_id": 94,
        "name": "Rakdos Control",
        "confidence": 0.72,
        "primary_strategy": "Control",
        "mechanics": ["Removal", "Treasure", "Recursion", "Burn"],
        "dominant_colors": ["B", "R"],
        "dominant_types": ["Land", "Creature", "Sorcery"],
        "tribe": None,
        "description": "Contrôle Rakdos (noir/rouge). Bedevil supprime, Blood Crypt et les fetchlands fixent le mana, Blood Money génère des Trésors en balayant.",
        "representative_cards": ["Bedevil", "Blood Crypt", "Blood Money", "Blackcleave Cliffs", "Balor"],
    },
    {
        "cluster_id": 66,
        "name": "Urza Tron Artifacts",
        "confidence": 0.94,
        "primary_strategy": "Artifacts",
        "mechanics": ["Urza Tron", "Artifact Synergy", "Colorless Mana", "Control"],
        "dominant_colors": ["U"],
        "dominant_types": ["Artifact", "Land"],
        "tribe": None,
        "description": "Archétype Urza Tron. Les terrains Urza (Mine, Tower, Power Plant) génèrent 7 mana ensemble, Whir of Invention cherche des artefacts, Urza, Lord Protector réduit les coûts.",
        "representative_cards": ["Urza's Tower", "Urza's Mine", "Urza's Power Plant", "Urza, Lord Protector", "Whir of Invention"],
    },
    {
        "cluster_id": 22,
        "name": "Selesnya Counters Aggro",
        "confidence": 0.76,
        "primary_strategy": "Aggro",
        "mechanics": ["+1/+1 Counters", "Evolve", "Exalted", "Anthem"],
        "dominant_colors": ["W", "G"],
        "dominant_types": ["Creature"],
        "tribe": None,
        "description": "Aggro blanc-vert par accumulation de compteurs. Experiment One évolue, Duelcraft Trainer donne le mentor, Dragonsguard Elite grossit avec chaque sort de dragon ou copie.",
        "representative_cards": ["Experiment One", "Duelcraft Trainer", "Dragonsguard Elite", "Fencing Ace", "Abzan Charm"],
    },
    {
        "cluster_id": 60,
        "name": "Azorius Blink Thassa",
        "confidence": 0.91,
        "primary_strategy": "Blink",
        "mechanics": ["Blink", "ETB", "Flicker", "Control"],
        "dominant_colors": ["W", "U"],
        "dominant_types": ["Creature", "Enchantment"],
        "tribe": None,
        "description": "Blink centré sur Thassa, Deep-Dwelling. Thassa exile une créature à chaque fin de tour pour relancer son ETB. Venser, Yorion et Teleportation Circle font de même.",
        "representative_cards": ["Thassa, Deep-Dwelling", "Venser, the Sojourner", "Yorion, Sky Nomad", "Venser, Shaper Savant", "Wan Shi Tong, All-Knowing"],
    },
    {
        "cluster_id": 14,
        "name": "Thopter Artifacts Blue",
        "confidence": 0.91,
        "primary_strategy": "Artifacts",
        "mechanics": ["Thopter", "Artifact Synergy", "Affinity", "Flying"],
        "dominant_colors": ["U"],
        "dominant_types": ["Artifact", "Creature"],
        "tribe": None,
        "description": "Fabrication de thoptères et artefacts bleus. Sai, Master Thopterist crée des thoptères, Simulacrum Synthesizer aussi, Sharding Sphinx double les tokens. Sharuum l'Hégémone réanime.",
        "representative_cards": ["Sai, Master Thopterist", "Simulacrum Synthesizer", "Sharding Sphinx", "Sharuum the Hegemon", "Shimmer Dragon"],
    },
    {
        "cluster_id": 12,
        "name": "Ninja Tribal",
        "confidence": 0.93,
        "primary_strategy": "Tribal",
        "mechanics": ["Ninjutsu", "Unblocked", "Card Draw", "ETB"],
        "dominant_colors": ["U", "B"],
        "dominant_types": ["Creature"],
        "tribe": "Ninja",
        "description": "Tribal ninja avec ninjutsu. Ninja of the Deep Hours et Moon-Circuit Hacker piocher quand ils touchent, Nashi ramène des sorts du cimetière, Ornithopter permet le ninjutsu au tour 1.",
        "representative_cards": ["Ninja of the Deep Hours", "Nashi, Moon Sage's Scion", "Moon-Circuit Hacker", "Ornithopter", "Moonblade Shinobi"],
    },
    {
        "cluster_id": 63,
        "name": "Mono Black Removal",
        "confidence": 0.77,
        "primary_strategy": "Control",
        "mechanics": ["Removal", "Graveyard", "Recursion", "Exile"],
        "dominant_colors": ["B"],
        "dominant_types": ["Instant", "Sorcery", "Creature"],
        "tribe": None,
        "description": "Suppression noire profonde. Extinction Event, Eat to Extinction et Drag to the Underworld gèrent toutes les menaces. Eradicator Valkyrie protège les ressources.",
        "representative_cards": ["Extinction Event", "Eat to Extinction", "Eradicator Valkyrie", "Entreat the Dead", "Ever After"],
    },
    {
        "cluster_id": 71,
        "name": "Ajani Planeswalker",
        "confidence": 0.95,
        "primary_strategy": "Autres",
        "mechanics": ["Planeswalker", "Counters", "Lifegain", "Token"],
        "dominant_colors": ["W", "G"],
        "dominant_types": ["Planeswalker"],
        "tribe": None,
        "description": "Cluster mono-thématique autour d'Ajani sous toutes ses formes. Ajani Mentor of Heroes, Steadfast, Caller of the Pride, Unyielding — convergence de planeswalkers d'une même lignée.",
        "representative_cards": ["Ajani, Mentor of Heroes", "Ajani Steadfast", "Ajani Unyielding", "Ajani, Caller of the Pride", "Ajani Goldmane"],
    },
    {
        "cluster_id": 29,
        "name": "Phyrexian Proliferate",
        "confidence": 0.91,
        "primary_strategy": "Combo",
        "mechanics": ["Proliferate", "Oil Counters", "Infect", "Poison"],
        "dominant_colors": ["G", "U", "W", "B"],
        "dominant_types": ["Creature", "Sorcery"],
        "tribe": None,
        "description": "Prolifération Phyrexienne moderne. Venerated Rotpriest brûle les adversaires à chaque ciblage, Tyrranax Rex prolifère en attaquant avec trample, Thrummingbird prolifère en combat.",
        "representative_cards": ["Venerated Rotpriest", "Tyrranax Rex", "Thrummingbird", "Viral Drake", "Vishgraz, the Doomhive"],
    },
    {
        "cluster_id": 8,
        "name": "Wheel Discard",
        "confidence": 0.92,
        "primary_strategy": "Combo",
        "mechanics": ["Wheel", "Discard", "Madness", "Drain"],
        "dominant_colors": ["U", "R"],
        "dominant_types": ["Creature", "Enchantment", "Sorcery"],
        "tribe": None,
        "description": "Archétype Wheel : forcer tout le monde à défausser et repiocher. Magus of the Wheel, Jace's Archivist, Megrim et Liliana's Caress drainent pour chaque carte défaussée par l'adversaire.",
        "representative_cards": ["Magus of the Wheel", "Jace's Archivist", "Liliana's Caress", "Megrim", "Kami of the Crescent Moon"],
    },
    {
        "cluster_id": 13,
        "name": "Dinosaur Jurassic",
        "confidence": 0.90,
        "primary_strategy": "Tribal",
        "mechanics": ["Dinosaur Synergy", "Ramp", "Enrage", "Big Creatures"],
        "dominant_colors": ["R", "G", "W"],
        "dominant_types": ["Creature", "Land"],
        "tribe": "Dinosaur",
        "description": "Dinosaures Jurassic Park. Regisaur Alpha donne haste à tous les dinos, Palani's Hatcher produit des oeufs, Polyraptor se multiplie à chaque dégât reçu.",
        "representative_cards": ["Regisaur Alpha", "Palani's Hatcher", "Polyraptor", "Quartzwood Crasher", "Raging Swordtooth"],
    },
    {
        "cluster_id": 18,
        "name": "Esper Artifacts Control",
        "confidence": 0.88,
        "primary_strategy": "Artifacts",
        "mechanics": ["Artifact Synergy", "Affinity", "Flying", "Control"],
        "dominant_colors": ["W", "U"],
        "dominant_types": ["Artifact", "Creature"],
        "tribe": None,
        "description": "Contrôle artefacts Azorius. Etherium Sculptor et Foundry Inspector réduisent les coûts, Emry recycle depuis le cimetière, Ethersworn Canonist limite les sorts adverses.",
        "representative_cards": ["Etherium Sculptor", "Foundry Inspector", "Emry, Lurker of the Loch", "Ethersworn Canonist", "Digsite Engineer"],
    },
    {
        "cluster_id": 41,
        "name": "Grixis Treasure",
        "confidence": 0.76,
        "primary_strategy": "Combo",
        "mechanics": ["Treasure", "Haste", "ETB", "Impulse Draw"],
        "dominant_colors": ["U", "B", "R"],
        "dominant_types": ["Creature", "Artifact"],
        "tribe": None,
        "description": "Trésors et valeur en Grixis. Juri grossit avec les sacrifices de Trésors, Kalain tire parti des Trésors pour placer des compteurs, Jolene et Korvold accumulent.",
        "representative_cards": ["Juri, Master of the Revue", "Kalain, Reclusive Painter", "Jolene, the Plunder Queen", "Light Up the Stage", "Laughing Jasper Flint"],
    },
    {
        "cluster_id": 97,
        "name": "Sacrifice Value",
        "confidence": 0.80,
        "primary_strategy": "Aristocrats",
        "mechanics": ["Sacrifice", "Token", "Graveyard", "ETB"],
        "dominant_colors": ["B", "G"],
        "dominant_types": ["Creature"],
        "tribe": None,
        "description": "Moteur sacrifice valeur noir-vert. Cauldron Familiar et Cauldron of Eternity reviennent indéfiniment, Catacomb Sifter scrye à chaque sacrifice, Bridge from Below génère des zombies depuis le cimetière.",
        "representative_cards": ["Cauldron Familiar", "Bridge from Below", "Catacomb Sifter", "Bone Shredder", "Chthonian Nightmare"],
    },
    {
        "cluster_id": 70,
        "name": "Titania Lands",
        "confidence": 0.92,
        "primary_strategy": "Lands",
        "mechanics": ["Landfall", "Sacrifice Land", "Token", "Ramp"],
        "dominant_colors": ["G", "U"],
        "dominant_types": ["Creature", "Land"],
        "tribe": None,
        "description": "Archétype Titania : sacrifier des terrains pour créer des jetons 5/3. Titania, Protector of Argoth crée des élémentaires quand des terrains vont au cimetière, Tireless Tracker génère des Indice.",
        "representative_cards": ["Titania, Protector of Argoth", "Tireless Tracker", "Tireless Provisioner", "Uro, Titan of Nature's Wrath", "Tiller Engine"],
    },
    {
        "cluster_id": 28,
        "name": "Grixis Wheel Pain",
        "confidence": 0.82,
        "primary_strategy": "Combo",
        "mechanics": ["Wheel", "Discard", "Damage", "Draw"],
        "dominant_colors": ["U", "B", "R"],
        "dominant_types": ["Creature", "Enchantment"],
        "tribe": None,
        "description": "Roues et douleur en Grixis. Sheoldred, the Apocalypse inflige 2 dégâts pour chaque carte piochée, Spiteful Visions blesse à chaque pioche, Seizan force la pioche et la douleur.",
        "representative_cards": ["Sheoldred, the Apocalypse", "Spiteful Visions", "Seizan, Perverter of Truth", "Solphim, Mayhem Dominus", "Sadistic Shell Game"],
    },
    {
        "cluster_id": 79,
        "name": "Golgari Graveyard",
        "confidence": 0.90,
        "primary_strategy": "Graveyard",
        "mechanics": ["Dredge", "Self-Mill", "Graveyard", "Token"],
        "dominant_colors": ["B", "G"],
        "dominant_types": ["Creature", "Sorcery"],
        "tribe": None,
        "description": "Archétype Dredge Golgari. Golgari Grave-Troll et Golgari Thug dredgent massivement, Grist est une créature dans le cimetière, Grim Flayer filtre la bibliothèque.",
        "representative_cards": ["Golgari Grave-Troll", "Golgari Thug", "Grist, Voracious Larva", "Grim Flayer", "Grapple with the Past"],
    },
    {
        "cluster_id": 47,
        "name": "Grixis Discard Draw",
        "confidence": 0.79,
        "primary_strategy": "Control",
        "mechanics": ["Discard", "Card Draw", "Madness", "Mill"],
        "dominant_colors": ["U", "B", "R"],
        "dominant_types": ["Sorcery", "Creature", "Instant"],
        "tribe": None,
        "description": "Pioche forcée et défausse en Grixis. Burning Inquiry fait défausser aléatoirement, Curiosity pioche à chaque dégât, Cruel Ultimatum dévaste les ressources adverses.",
        "representative_cards": ["Burning Inquiry", "Curiosity", "Cruel Ultimatum", "Dack Fayden", "Consult the Necrosages"],
    },
    {
        "cluster_id": 20,
        "name": "Colorless Artifact Ramp",
        "confidence": 0.77,
        "primary_strategy": "Artifacts",
        "mechanics": ["Colorless Mana", "Artifact Synergy", "Ramp", "Eldrazi"],
        "dominant_colors": ["C"],
        "dominant_types": ["Artifact", "Creature", "Land"],
        "tribe": None,
        "description": "Rampe par artefacts incolores. Hedron Archive, Guardian Idol et Hexavus accélèrent le mana, Hand of Vecna équipe automatiquement, Graaz, Unstoppable Juggernaut est une bombe à zéro coût.",
        "representative_cards": ["Hedron Archive", "Hexavus", "Graaz, Unstoppable Juggernaut", "Hand of Vecna", "Golem Foundry"],
    },
    {
        "cluster_id": 89,
        "name": "Golgari Sacrifice Small",
        "confidence": 0.72,
        "primary_strategy": "Aristocrats",
        "mechanics": ["Sacrifice", "ETB", "Graveyard", "Token"],
        "dominant_colors": ["B", "G"],
        "dominant_types": ["Creature"],
        "tribe": None,
        "description": "Petit moteur sacrifice vert-noir. Evolutionary Leap échange une créature contre une autre depuis la bibliothèque, Finale of Eternity réanime massivement, Foundation Breaker rampe.",
        "representative_cards": ["Evolutionary Leap", "Finale of Eternity", "Ethereal Investigator", "Find // Finality", "Feral Prowler"],
    },
    {
        "cluster_id": 83,
        "name": "Azorius Prison",
        "confidence": 0.75,
        "primary_strategy": "Control",
        "mechanics": ["Prison", "Tax", "Bounce", "Flash"],
        "dominant_colors": ["W", "U"],
        "dominant_types": ["Creature", "Enchantment"],
        "tribe": None,
        "description": "Prison blanc-bleu. Kataki, War's Wage taxe les artefacts, Lavinia of the Tenth empêche les sorts sans mana, Lumbering Battlement exile les créatures alliées pour revenir en force.",
        "representative_cards": ["Kataki, War's Wage", "Lavinia of the Tenth", "Lumbering Battlement", "Isperia, Supreme Judge", "Kitchen Finks"],
    },
    {
        "cluster_id": 50,
        "name": "Black Death Utility",
        "confidence": 0.72,
        "primary_strategy": "Graveyard",
        "mechanics": ["Sacrifice", "Recursion", "Instant Death", "Drain"],
        "dominant_colors": ["B"],
        "dominant_types": ["Instant", "Sorcery", "Creature"],
        "tribe": None,
        "description": "Utilitaires noirs autour de la mort : Feign Death et Fake Your Own Death protègent, Exsanguinate draine massivement, Final Act sacrifie les créatures d'un joueur choisi.",
        "representative_cards": ["Exsanguinate", "Feign Death", "Fake Your Own Death", "Final Act", "Fain, the Broker"],
    },
    {
        "cluster_id": 84,
        "name": "Elf Tribal Wirewood",
        "confidence": 0.96,
        "primary_strategy": "Tribal",
        "mechanics": ["Elf Synergy", "Untap", "Ramp", "Swarm"],
        "dominant_colors": ["G"],
        "dominant_types": ["Creature"],
        "tribe": "Elf",
        "description": "Elfes Wirewood Lorwyn. Wirewood Symbiote retourne un elfe en main pour untaper un autre elfe, Wirewood Lodge untape Elvish Archdruid, Wirewood Hivemaster crée des insectes.",
        "representative_cards": ["Wirewood Symbiote", "Wirewood Lodge", "Wirewood Channeler", "Wren's Run Vanquisher", "Wirewood Hivemaster"],
    },
    {
        "cluster_id": 57,
        "name": "Mono White Life",
        "confidence": 0.74,
        "primary_strategy": "Control",
        "mechanics": ["Lifegain", "Recursion", "Exile", "Protection"],
        "dominant_colors": ["W"],
        "dominant_types": ["Creature", "Instant", "Enchantment"],
        "tribe": None,
        "description": "Gain de vie mono-blanc utilitaire. Selfless Savior protège, Serra Avatar grossit avec la vie, Righteous Confluence gère le board, Sage's Reverie donne des auras et pioche.",
        "representative_cards": ["Serra Avatar", "Selfless Savior", "Righteous Confluence", "Scourge of the Nobilis", "Sage's Reverie"],
    },
    {
        "cluster_id": 82,
        "name": "Ninja Rogue Kaito",
        "confidence": 0.88,
        "primary_strategy": "Tribal",
        "mechanics": ["Ninjutsu", "Unblocked", "Discard Draw", "Evasion"],
        "dominant_colors": ["U", "B"],
        "dominant_types": ["Creature"],
        "tribe": "Ninja",
        "description": "Ninjas et rôdeurs bleu-noir version Kamigawa Neon Dynasty. Kaito sous toutes ses formes (Shizuki, Dancing Shadow, Cunning Infiltrator) pioche et place des marqueurs.",
        "representative_cards": ["Kaito, Bane of Nightmares", "Kaito Shizuki", "Kaito, Dancing Shadow", "Ink-Eyes, Servant of Oni", "Invisible Stalker"],
    },
    {
        "cluster_id": 1,
        "name": "Orc Tribal",
        "confidence": 0.97,
        "primary_strategy": "Tribal",
        "mechanics": ["Orc Synergy", "Aggro", "Haste"],
        "dominant_colors": ["R"],
        "dominant_types": ["Creature"],
        "tribe": "Orc",
        "description": "Tribal Orc mono-rouge très concentré. Cluster de niche avec Port Razer (donne des combats supplémentaires), Orcish Siegemaster, Ork Kommando — toutes des cartes Orc.",
        "representative_cards": ["Port Razer", "Orcish Siegemaster", "Ork Kommando", "Orc Sureshot", "Plargg, Dean of Chaos"],
    },
    {
        "cluster_id": 35,
        "name": "Mardu Warriors Small",
        "confidence": 0.83,
        "primary_strategy": "Aggro",
        "mechanics": ["Warrior Synergy", "Combat", "Haste", "Lifelink"],
        "dominant_colors": ["W", "B", "R"],
        "dominant_types": ["Creature", "Artifact"],
        "tribe": "Warrior",
        "description": "Petit cluster Mardu guerrier. Maul of the Skyclaves et Mauhúr, Uruk-hai Captain représentent les guerriers uruk-haï, Mardu Strike Leader crée des guerriers en blitz.",
        "representative_cards": ["Maul of the Skyclaves", "Mauhúr, Uruk-hai Captain", "Mardu Strike Leader", "Master Warcraft", "Mardu Charm"],
    },
    {
        "cluster_id": 96,
        "name": "Zombie Tribal Core",
        "confidence": 0.94,
        "primary_strategy": "Tribal",
        "mechanics": ["Zombie Synergy", "Token", "Graveyard", "Lord"],
        "dominant_colors": ["B", "U"],
        "dominant_types": ["Creature"],
        "tribe": "Zombie",
        "description": "Noyau tribal zombie. Diregraf Captain et Death Baron sont les lords, Diregraf Colossus crée des jetons à chaque zombie joué, Cryptbreaker génère des zombies et pioche.",
        "representative_cards": ["Diregraf Captain", "Death Baron", "Diregraf Colossus", "Cryptbreaker", "Crowded Crypt"],
    },
]

TAXONOMY_FAMILIES_LIST = [
    "Tribal", "Graveyard", "Blink", "Aristocrats", "Tokens",
    "Lands", "Artifacts", "Enchantments", "Spellslinger", "Combo",
    "Ramp", "Control", "Aggro", "Autres",
]


def main() -> None:
    log.info("=== generate_annotations.py ===")

    summary = pd.read_csv(SUMMARY, encoding="utf-8")
    size_map = dict(zip(summary["cluster_id"].astype(int), summary["cluster_size"].astype(int)))
    freq_map = dict(zip(summary["cluster_id"].astype(int), summary["avg_frequency"].astype(float)))
    idf_map  = dict(zip(summary["cluster_id"].astype(int), summary["avg_idf"].astype(float)))

    # Enrichir les annotations avec les métadonnées du summary
    annotations = []
    for ann in RAW_ANNOTATIONS:
        cid = ann["cluster_id"]
        ann["cluster_size"]  = size_map.get(cid, 0)
        ann["avg_frequency"] = round(freq_map.get(cid, 0.0), 4)
        ann["avg_idf"]       = round(idf_map.get(cid, 0.0), 4)
        annotations.append(ann)

    annotations.sort(key=lambda x: x["cluster_id"])
    log.info("Annotations generees : %d clusters", len(annotations))

    # Sauvegarde
    OUT_ANNOT.write_text(
        json.dumps(annotations, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    log.info("Ecrit : cluster_annotations.json")

    # ── Taxonomie ─────────────────────────────────────────────────────────────
    family_map: dict[str, list[dict]] = {f: [] for f in TAXONOMY_FAMILIES_LIST}
    for ann in annotations:
        strat = ann.get("primary_strategy", "Autres")
        if strat not in family_map:
            strat = "Autres"
        family_map[strat].append({
            "cluster_id":   ann["cluster_id"],
            "name":         ann["name"],
            "cluster_size": ann["cluster_size"],
            "confidence":   ann["confidence"],
            "tribe":        ann.get("tribe"),
            "mechanics":    ann["mechanics"],
            "description":  ann["description"],
        })

    taxonomy = {
        "total_clusters": len(annotations),
        "total_cards_assigned": sum(a["cluster_size"] for a in annotations),
        "families": {},
    }
    for family in TAXONOMY_FAMILIES_LIST:
        members = family_map[family]
        if not members:
            continue
        members_sorted = sorted(members, key=lambda x: x["cluster_size"], reverse=True)
        taxonomy["families"][family] = {
            "cluster_count":  len(members),
            "total_cards":    sum(m["cluster_size"] for m in members),
            "avg_confidence": round(sum(m["confidence"] for m in members) / len(members), 3),
            "clusters":       members_sorted,
        }

    OUT_TAXO.write_text(
        json.dumps(taxonomy, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    log.info("Ecrit : cluster_taxonomy.json")

    log.info("--- Taxonomie ---")
    for fam, data in sorted(taxonomy["families"].items(), key=lambda x: -x[1]["cluster_count"]):
        log.info("  %-15s  %3d clusters  %5d cartes  conf=%.2f",
                 fam, data["cluster_count"], data["total_cards"], data["avg_confidence"])

    log.info("=== Termine ===")


if __name__ == "__main__":
    main()
